// Code generated by protoc-gen-go-styx. DO NOT EDIT.
// source: examples/echo/echo.proto

package echopb

import (
	context "context"
	styx "github.com/arloliu/styx"
	proto "google.golang.org/protobuf/proto"
)

// StyxGeneratorVersion and StyxRuntimeABIVersion are write-only for now:
// nothing in the handshake reads them back yet. A later change makes the
// handshake cross-check them against the host's own build to catch
// generator/runtime ABI drift as a clean incompatibility.
const (
	StyxGeneratorVersion  = "v1"
	StyxRuntimeABIVersion = 1
)

const (
	echoServiceID      uint64 = 0xedc54b402664edff // fnv1a64("echo.Echo")
	echoSayMethodID    uint64 = 0x9836aa19fa8ee240 // fnv1a64("Say")
	EchoServiceVersion uint32 = 1
)

func EchoRequirement() styx.ServiceRequirement {
	return styx.ServiceRequirement{
		Service:    "echo.Echo",
		MinVersion: EchoServiceVersion,
		MaxVersion: EchoServiceVersion,
	}
}

type EchoClient interface {
	Say(ctx context.Context, req *SayRequest) (*SayResponse, error)
}

type echoClient struct{ conn *styx.ClientConn }

func NewEchoClient(conn *styx.ClientConn) EchoClient { return &echoClient{conn: conn} }

func (c *echoClient) Say(ctx context.Context, req *SayRequest) (*SayResponse, error) {
	resp := &SayResponse{}
	if err := c.conn.Invoke(ctx, "echo.Echo", "Say", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type EchoServer interface {
	Say(ctx context.Context, req *SayRequest) (*SayResponse, error)
}

func RegisterEchoServer(srv *styx.PluginServer, impl EchoServer) {
	srv.RegisterService(&styx.ServiceDesc{
		ServiceName: "echo.Echo",
		ServiceID:   echoServiceID,
		Version:     EchoServiceVersion,
		Methods: []styx.MethodDesc{
			{
				MethodName: "Say",
				MethodID:   echoSayMethodID,
				Handler: func(s any, ctx context.Context, dec func(proto.Message) error) (proto.Message, error) {
					req := &SayRequest{}
					if err := dec(req); err != nil {
						return nil, err
					}
					return impl.Say(ctx, req)
				},
			},
		},
	}, impl)
}
