// Code generated by protoc-gen-go-styx. DO NOT EDIT.
// source: examples/device-gateway/deviceplugin/device_plugin.proto

package deviceplugin

import (
	context "context"
	styx "github.com/arloliu/styx"
	proto "google.golang.org/protobuf/proto"
)

// StyxGeneratorVersion and StyxRuntimeABIVersion are write-only for now:
// nothing in the handshake reads them back yet. A later change makes the
// handshake cross-check them against the host's own build to catch
// generator/runtime ABI drift as a clean incompatibility.
const (
	StyxGeneratorVersion  = "v1"
	StyxRuntimeABIVersion = 1
)

const (
	devicePluginServiceID                       = 0xa6533f520ec140e7 // fnv1a64("deviceplugin.DevicePlugin")
	devicePluginInitMethodID                    = 0x2060b0d17c25e5f3 // fnv1a64("Init")
	devicePluginMetadataMethodID                = 0x252a52330d32b900 // fnv1a64("Metadata")
	devicePluginSetLogLevelMethodID             = 0x954453fbeabb95d3 // fnv1a64("SetLogLevel")
	devicePluginStartMethodID                   = 0xae1c7f13b7c0c47f // fnv1a64("Start")
	devicePluginStopMethodID                    = 0xd9ad53251f2330a5 // fnv1a64("Stop")
	devicePluginPauseMethodID                   = 0x61cc20e3432dead  // fnv1a64("Pause")
	devicePluginHotReloadMethodID               = 0x870475d9b91832f9 // fnv1a64("HotReload")
	devicePluginLoadRuntimeStateMethodID        = 0xd4770ce3e50ea2c0 // fnv1a64("LoadRuntimeState")
	devicePluginSaveRuntimeStateMethodID        = 0x85d243d193951c81 // fnv1a64("SaveRuntimeState")
	devicePluginCollectMetricsMethodID          = 0xea9914711e5c9e2  // fnv1a64("CollectMetrics")
	DevicePluginServiceVersion           uint32 = 1
)

const DevicePluginRequiresStreaming = false

func DevicePluginRequirement() styx.ServiceRequirement {
	return styx.ServiceRequirement{
		Service:    "deviceplugin.DevicePlugin",
		MinVersion: DevicePluginServiceVersion,
		MaxVersion: DevicePluginServiceVersion,
	}
}

type DevicePluginClient interface {
	Init(ctx context.Context, req *InitRequest) (*Empty, error)
	Metadata(ctx context.Context, req *Empty) (*MetadataResponse, error)
	SetLogLevel(ctx context.Context, req *LogLevelRequest) (*Empty, error)
	Start(ctx context.Context, req *Empty) (*Empty, error)
	Stop(ctx context.Context, req *Empty) (*Empty, error)
	Pause(ctx context.Context, req *Empty) (*Empty, error)
	HotReload(ctx context.Context, req *HotReloadRequest) (*Empty, error)
	LoadRuntimeState(ctx context.Context, req *RuntimeState) (*Empty, error)
	SaveRuntimeState(ctx context.Context, req *Empty) (*RuntimeState, error)
	CollectMetrics(ctx context.Context, req *Empty) (*MetricsSnapshot, error)
}

type devicePluginClient struct{ conn *styx.ClientConn }

func NewDevicePluginClient(conn *styx.ClientConn) DevicePluginClient {
	return &devicePluginClient{conn: conn}
}

func (c *devicePluginClient) Init(ctx context.Context, req *InitRequest) (*Empty, error) {
	msg, err := c.conn.InvokeIDFactory(ctx, devicePluginServiceID, devicePluginInitMethodID, req, func() proto.Message { return &Empty{} })
	if err != nil {
		return nil, err
	}
	return msg.(*Empty), nil
}

func (c *devicePluginClient) Metadata(ctx context.Context, req *Empty) (*MetadataResponse, error) {
	msg, err := c.conn.InvokeIDFactory(ctx, devicePluginServiceID, devicePluginMetadataMethodID, req, func() proto.Message { return &MetadataResponse{} })
	if err != nil {
		return nil, err
	}
	return msg.(*MetadataResponse), nil
}

func (c *devicePluginClient) SetLogLevel(ctx context.Context, req *LogLevelRequest) (*Empty, error) {
	msg, err := c.conn.InvokeIDFactory(ctx, devicePluginServiceID, devicePluginSetLogLevelMethodID, req, func() proto.Message { return &Empty{} })
	if err != nil {
		return nil, err
	}
	return msg.(*Empty), nil
}

func (c *devicePluginClient) Start(ctx context.Context, req *Empty) (*Empty, error) {
	msg, err := c.conn.InvokeIDFactory(ctx, devicePluginServiceID, devicePluginStartMethodID, req, func() proto.Message { return &Empty{} })
	if err != nil {
		return nil, err
	}
	return msg.(*Empty), nil
}

func (c *devicePluginClient) Stop(ctx context.Context, req *Empty) (*Empty, error) {
	msg, err := c.conn.InvokeIDFactory(ctx, devicePluginServiceID, devicePluginStopMethodID, req, func() proto.Message { return &Empty{} })
	if err != nil {
		return nil, err
	}
	return msg.(*Empty), nil
}

func (c *devicePluginClient) Pause(ctx context.Context, req *Empty) (*Empty, error) {
	msg, err := c.conn.InvokeIDFactory(ctx, devicePluginServiceID, devicePluginPauseMethodID, req, func() proto.Message { return &Empty{} })
	if err != nil {
		return nil, err
	}
	return msg.(*Empty), nil
}

func (c *devicePluginClient) HotReload(ctx context.Context, req *HotReloadRequest) (*Empty, error) {
	msg, err := c.conn.InvokeIDFactory(ctx, devicePluginServiceID, devicePluginHotReloadMethodID, req, func() proto.Message { return &Empty{} })
	if err != nil {
		return nil, err
	}
	return msg.(*Empty), nil
}

func (c *devicePluginClient) LoadRuntimeState(ctx context.Context, req *RuntimeState) (*Empty, error) {
	msg, err := c.conn.InvokeIDFactory(ctx, devicePluginServiceID, devicePluginLoadRuntimeStateMethodID, req, func() proto.Message { return &Empty{} })
	if err != nil {
		return nil, err
	}
	return msg.(*Empty), nil
}

func (c *devicePluginClient) SaveRuntimeState(ctx context.Context, req *Empty) (*RuntimeState, error) {
	msg, err := c.conn.InvokeIDFactory(ctx, devicePluginServiceID, devicePluginSaveRuntimeStateMethodID, req, func() proto.Message { return &RuntimeState{} })
	if err != nil {
		return nil, err
	}
	return msg.(*RuntimeState), nil
}

func (c *devicePluginClient) CollectMetrics(ctx context.Context, req *Empty) (*MetricsSnapshot, error) {
	msg, err := c.conn.InvokeIDFactory(ctx, devicePluginServiceID, devicePluginCollectMetricsMethodID, req, func() proto.Message { return &MetricsSnapshot{} })
	if err != nil {
		return nil, err
	}
	return msg.(*MetricsSnapshot), nil
}

type DevicePluginServer interface {
	Init(ctx context.Context, req *InitRequest) (*Empty, error)
	Metadata(ctx context.Context, req *Empty) (*MetadataResponse, error)
	SetLogLevel(ctx context.Context, req *LogLevelRequest) (*Empty, error)
	Start(ctx context.Context, req *Empty) (*Empty, error)
	Stop(ctx context.Context, req *Empty) (*Empty, error)
	Pause(ctx context.Context, req *Empty) (*Empty, error)
	HotReload(ctx context.Context, req *HotReloadRequest) (*Empty, error)
	LoadRuntimeState(ctx context.Context, req *RuntimeState) (*Empty, error)
	SaveRuntimeState(ctx context.Context, req *Empty) (*RuntimeState, error)
	CollectMetrics(ctx context.Context, req *Empty) (*MetricsSnapshot, error)
}

func RegisterDevicePluginServer(srv *styx.PluginServer, impl DevicePluginServer) {
	srv.RegisterService(&styx.ServiceDesc{
		ServiceName: "deviceplugin.DevicePlugin",
		ServiceID:   devicePluginServiceID,
		Version:     DevicePluginServiceVersion,
		Methods: []styx.MethodDesc{
			{
				MethodName: "Init",
				MethodID:   devicePluginInitMethodID,
				NewRequest: func() proto.Message { return &InitRequest{} },
				Handler: func(s any, ctx context.Context, req proto.Message) (proto.Message, error) {
					return impl.Init(ctx, req.(*InitRequest))
				},
			},
			{
				MethodName: "Metadata",
				MethodID:   devicePluginMetadataMethodID,
				NewRequest: func() proto.Message { return &Empty{} },
				Handler: func(s any, ctx context.Context, req proto.Message) (proto.Message, error) {
					return impl.Metadata(ctx, req.(*Empty))
				},
			},
			{
				MethodName: "SetLogLevel",
				MethodID:   devicePluginSetLogLevelMethodID,
				NewRequest: func() proto.Message { return &LogLevelRequest{} },
				Handler: func(s any, ctx context.Context, req proto.Message) (proto.Message, error) {
					return impl.SetLogLevel(ctx, req.(*LogLevelRequest))
				},
			},
			{
				MethodName: "Start",
				MethodID:   devicePluginStartMethodID,
				NewRequest: func() proto.Message { return &Empty{} },
				Handler: func(s any, ctx context.Context, req proto.Message) (proto.Message, error) {
					return impl.Start(ctx, req.(*Empty))
				},
			},
			{
				MethodName: "Stop",
				MethodID:   devicePluginStopMethodID,
				NewRequest: func() proto.Message { return &Empty{} },
				Handler: func(s any, ctx context.Context, req proto.Message) (proto.Message, error) {
					return impl.Stop(ctx, req.(*Empty))
				},
			},
			{
				MethodName: "Pause",
				MethodID:   devicePluginPauseMethodID,
				NewRequest: func() proto.Message { return &Empty{} },
				Handler: func(s any, ctx context.Context, req proto.Message) (proto.Message, error) {
					return impl.Pause(ctx, req.(*Empty))
				},
			},
			{
				MethodName: "HotReload",
				MethodID:   devicePluginHotReloadMethodID,
				NewRequest: func() proto.Message { return &HotReloadRequest{} },
				Handler: func(s any, ctx context.Context, req proto.Message) (proto.Message, error) {
					return impl.HotReload(ctx, req.(*HotReloadRequest))
				},
			},
			{
				MethodName: "LoadRuntimeState",
				MethodID:   devicePluginLoadRuntimeStateMethodID,
				NewRequest: func() proto.Message { return &RuntimeState{} },
				Handler: func(s any, ctx context.Context, req proto.Message) (proto.Message, error) {
					return impl.LoadRuntimeState(ctx, req.(*RuntimeState))
				},
			},
			{
				MethodName: "SaveRuntimeState",
				MethodID:   devicePluginSaveRuntimeStateMethodID,
				NewRequest: func() proto.Message { return &Empty{} },
				Handler: func(s any, ctx context.Context, req proto.Message) (proto.Message, error) {
					return impl.SaveRuntimeState(ctx, req.(*Empty))
				},
			},
			{
				MethodName: "CollectMetrics",
				MethodID:   devicePluginCollectMetricsMethodID,
				NewRequest: func() proto.Message { return &Empty{} },
				Handler: func(s any, ctx context.Context, req proto.Message) (proto.Message, error) {
					return impl.CollectMetrics(ctx, req.(*Empty))
				},
			},
		},
	}, impl)
}

func init() {
	styx.RegisterIdentityName(devicePluginServiceID, "deviceplugin.DevicePlugin")
	styx.RegisterIdentityName(devicePluginInitMethodID, "Init")
	styx.RegisterIdentityName(devicePluginMetadataMethodID, "Metadata")
	styx.RegisterIdentityName(devicePluginSetLogLevelMethodID, "SetLogLevel")
	styx.RegisterIdentityName(devicePluginStartMethodID, "Start")
	styx.RegisterIdentityName(devicePluginStopMethodID, "Stop")
	styx.RegisterIdentityName(devicePluginPauseMethodID, "Pause")
	styx.RegisterIdentityName(devicePluginHotReloadMethodID, "HotReload")
	styx.RegisterIdentityName(devicePluginLoadRuntimeStateMethodID, "LoadRuntimeState")
	styx.RegisterIdentityName(devicePluginSaveRuntimeStateMethodID, "SaveRuntimeState")
	styx.RegisterIdentityName(devicePluginCollectMetricsMethodID, "CollectMetrics")
}
