// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: examples/device-gateway/deviceplugin/device_plugin.proto

package deviceplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescGZIP(), []int{0}
}

// MetricConfig is the structured metrics configuration Init carries,
// matching the real contract's own message shape field for field.
type MetricConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ConstLabels   map[string]string      `protobuf:"bytes,2,rep,name=const_labels,json=constLabels,proto3" json:"const_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricConfig) Reset() {
	*x = MetricConfig{}
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricConfig) ProtoMessage() {}

func (x *MetricConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricConfig.ProtoReflect.Descriptor instead.
func (*MetricConfig) Descriptor() ([]byte, []int) {
	return file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *MetricConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MetricConfig) GetConstLabels() map[string]string {
	if x != nil {
		return x.ConstLabels
	}
	return nil
}

func (x *MetricConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// InitRequest carries a device's configuration. device_config is opaque to
// Styx and to this contract — its shape is whatever the plugin and the host
// application agree on (JSON, another protobuf message, anything), matching
// the real contract's own opaque-bytes convention. metric_config is
// structured, also matching the real contract.
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceConfig  []byte                 `protobuf:"bytes,1,opt,name=device_config,json=deviceConfig,proto3" json:"device_config,omitempty"`
	MetricConfig  *MetricConfig          `protobuf:"bytes,2,opt,name=metric_config,json=metricConfig,proto3" json:"metric_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetDeviceConfig() []byte {
	if x != nil {
		return x.DeviceConfig
	}
	return nil
}

func (x *InitRequest) GetMetricConfig() *MetricConfig {
	if x != nil {
		return x.MetricConfig
	}
	return nil
}

// MetadataResponse is the instance's identity. host_version is a generic
// rename of the real contract's own field, which names the field after that
// specific gateway; the meaning is the same — the framework/build version
// the plugin was validated against. This contract omits the real
// response's nested capability-attributes sub-message, since Attributes is
// separately out of scope (see the service comment above): a caller
// wanting capability flags would call a future Attributes RPC, not parse
// them out of Metadata.
type MetadataResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion uint64                 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	HostVersion     string                 `protobuf:"bytes,4,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetadataResponse) GetProtocolVersion() uint64 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *MetadataResponse) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

// LogLevelRequest names the level to switch to, e.g. "debug", "info",
// "warn", "error", "fatal" — a plain string in both contracts, not an enum.
type LogLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelRequest) Reset() {
	*x = LogLevelRequest{}
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelRequest) ProtoMessage() {}

func (x *LogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelRequest.ProtoReflect.Descriptor instead.
func (*LogLevelRequest) Descriptor() ([]byte, []int) {
	return file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *LogLevelRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

// HotReloadRequest carries a device's replacement configuration.
type HotReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceConfig  []byte                 `protobuf:"bytes,1,opt,name=device_config,json=deviceConfig,proto3" json:"device_config,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotReloadRequest) Reset() {
	*x = HotReloadRequest{}
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotReloadRequest) ProtoMessage() {}

func (x *HotReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotReloadRequest.ProtoReflect.Descriptor instead.
func (*HotReloadRequest) Descriptor() ([]byte, []int) {
	return file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HotReloadRequest) GetDeviceConfig() []byte {
	if x != nil {
		return x.DeviceConfig
	}
	return nil
}

func (x *HotReloadRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// RuntimeState is a single opaque snapshot of a device's runtime state.
// device_version matches the real contract exactly: the device driver's own
// version string (the same value Metadata.version returns), not a snapshot
// format number. snapshot_format_version is an addition beyond the real
// contract — this pilot's own envelope-version guard for how the opaque
// state bytes are encoded, layered on top of (not replacing) device_version.
type RuntimeState struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DeviceVersion         string                 `protobuf:"bytes,1,opt,name=device_version,json=deviceVersion,proto3" json:"device_version,omitempty"`
	State                 []byte                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	SnapshotFormatVersion uint32                 `protobuf:"varint,3,opt,name=snapshot_format_version,json=snapshotFormatVersion,proto3" json:"snapshot_format_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RuntimeState) Reset() {
	*x = RuntimeState{}
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeState) ProtoMessage() {}

func (x *RuntimeState) ProtoReflect() protoreflect.Message {
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeState.ProtoReflect.Descriptor instead.
func (*RuntimeState) Descriptor() ([]byte, []int) {
	return file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *RuntimeState) GetDeviceVersion() string {
	if x != nil {
		return x.DeviceVersion
	}
	return ""
}

func (x *RuntimeState) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *RuntimeState) GetSnapshotFormatVersion() uint32 {
	if x != nil {
		return x.SnapshotFormatVersion
	}
	return 0
}

// MetricsSnapshot carries the plugin's metrics as a list of opaque,
// pre-serialized entries. The real contract's plugins serialize a Prometheus
// MetricFamily into each one; this contract does not require that shape —
// interpreting the bytes is the host application's job, same as it is today.
type MetricsSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MetricFamilies [][]byte               `protobuf:"bytes,1,rep,name=metric_families,json=metricFamilies,proto3" json:"metric_families,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsSnapshot) Reset() {
	*x = MetricsSnapshot{}
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSnapshot) ProtoMessage() {}

func (x *MetricsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSnapshot.ProtoReflect.Descriptor instead.
func (*MetricsSnapshot) Descriptor() ([]byte, []int) {
	return file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsSnapshot) GetMetricFamilies() [][]byte {
	if x != nil {
		return x.MetricFamilies
	}
	return nil
}

var File_examples_device_gateway_deviceplugin_device_plugin_proto protoreflect.FileDescriptor

const file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDesc = "" +
	"\n" +
	"8examples/device-gateway/deviceplugin/device_plugin.proto\x12\fdeviceplugin\"\a\n" +
	"\x05Empty\"\xd6\x01\n" +
	"\fMetricConfig\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12N\n" +
	"\fconst_labels\x18\x02 \x03(\v2+.deviceplugin.MetricConfig.ConstLabelsEntryR\vconstLabels\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x1a>\n" +
	"\x10ConstLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\vInitRequest\x12#\n" +
	"\rdevice_config\x18\x01 \x01(\fR\fdeviceConfig\x12?\n" +
	"\rmetric_config\x18\x02 \x01(\v2\x1a.deviceplugin.MetricConfigR\fmetricConfig\"\x8e\x01\n" +
	"\x10MetadataResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\x04R\x0fprotocolVersion\x12!\n" +
	"\fhost_version\x18\x04 \x01(\tR\vhostVersion\"'\n" +
	"\x0fLogLevelRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\"P\n" +
	"\x10HotReloadRequest\x12#\n" +
	"\rdevice_config\x18\x01 \x01(\fR\fdeviceConfig\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"\x83\x01\n" +
	"\fRuntimeState\x12%\n" +
	"\x0edevice_version\x18\x01 \x01(\tR\rdeviceVersion\x12\x14\n" +
	"\x05state\x18\x02 \x01(\fR\x05state\x126\n" +
	"\x17snapshot_format_version\x18\x03 \x01(\rR\x15snapshotFormatVersion\":\n" +
	"\x0fMetricsSnapshot\x12'\n" +
	"\x0fmetric_families\x18\x01 \x03(\fR\x0emetricFamilies2\xf4\x04\n" +
	"\fDevicePlugin\x126\n" +
	"\x04Init\x12\x19.deviceplugin.InitRequest\x1a\x13.deviceplugin.Empty\x12?\n" +
	"\bMetadata\x12\x13.deviceplugin.Empty\x1a\x1e.deviceplugin.MetadataResponse\x12A\n" +
	"\vSetLogLevel\x12\x1d.deviceplugin.LogLevelRequest\x1a\x13.deviceplugin.Empty\x121\n" +
	"\x05Start\x12\x13.deviceplugin.Empty\x1a\x13.deviceplugin.Empty\x120\n" +
	"\x04Stop\x12\x13.deviceplugin.Empty\x1a\x13.deviceplugin.Empty\x121\n" +
	"\x05Pause\x12\x13.deviceplugin.Empty\x1a\x13.deviceplugin.Empty\x12@\n" +
	"\tHotReload\x12\x1e.deviceplugin.HotReloadRequest\x1a\x13.deviceplugin.Empty\x12C\n" +
	"\x10LoadRuntimeState\x12\x1a.deviceplugin.RuntimeState\x1a\x13.deviceplugin.Empty\x12C\n" +
	"\x10SaveRuntimeState\x12\x13.deviceplugin.Empty\x1a\x1a.deviceplugin.RuntimeState\x12D\n" +
	"\x0eCollectMetrics\x12\x13.deviceplugin.Empty\x1a\x1d.deviceplugin.MetricsSnapshotB>Z<github.com/arloliu/styx/examples/device-gateway/devicepluginb\x06proto3"

var (
	file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescOnce sync.Once
	file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescData []byte
)

func file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescGZIP() []byte {
	file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescOnce.Do(func() {
		file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDesc), len(file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDesc)))
	})
	return file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDescData
}

var file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_examples_device_gateway_deviceplugin_device_plugin_proto_goTypes = []any{
	(*Empty)(nil),            // 0: deviceplugin.Empty
	(*MetricConfig)(nil),     // 1: deviceplugin.MetricConfig
	(*InitRequest)(nil),      // 2: deviceplugin.InitRequest
	(*MetadataResponse)(nil), // 3: deviceplugin.MetadataResponse
	(*LogLevelRequest)(nil),  // 4: deviceplugin.LogLevelRequest
	(*HotReloadRequest)(nil), // 5: deviceplugin.HotReloadRequest
	(*RuntimeState)(nil),     // 6: deviceplugin.RuntimeState
	(*MetricsSnapshot)(nil),  // 7: deviceplugin.MetricsSnapshot
	nil,                      // 8: deviceplugin.MetricConfig.ConstLabelsEntry
}
var file_examples_device_gateway_deviceplugin_device_plugin_proto_depIdxs = []int32{
	8,  // 0: deviceplugin.MetricConfig.const_labels:type_name -> deviceplugin.MetricConfig.ConstLabelsEntry
	1,  // 1: deviceplugin.InitRequest.metric_config:type_name -> deviceplugin.MetricConfig
	2,  // 2: deviceplugin.DevicePlugin.Init:input_type -> deviceplugin.InitRequest
	0,  // 3: deviceplugin.DevicePlugin.Metadata:input_type -> deviceplugin.Empty
	4,  // 4: deviceplugin.DevicePlugin.SetLogLevel:input_type -> deviceplugin.LogLevelRequest
	0,  // 5: deviceplugin.DevicePlugin.Start:input_type -> deviceplugin.Empty
	0,  // 6: deviceplugin.DevicePlugin.Stop:input_type -> deviceplugin.Empty
	0,  // 7: deviceplugin.DevicePlugin.Pause:input_type -> deviceplugin.Empty
	5,  // 8: deviceplugin.DevicePlugin.HotReload:input_type -> deviceplugin.HotReloadRequest
	6,  // 9: deviceplugin.DevicePlugin.LoadRuntimeState:input_type -> deviceplugin.RuntimeState
	0,  // 10: deviceplugin.DevicePlugin.SaveRuntimeState:input_type -> deviceplugin.Empty
	0,  // 11: deviceplugin.DevicePlugin.CollectMetrics:input_type -> deviceplugin.Empty
	0,  // 12: deviceplugin.DevicePlugin.Init:output_type -> deviceplugin.Empty
	3,  // 13: deviceplugin.DevicePlugin.Metadata:output_type -> deviceplugin.MetadataResponse
	0,  // 14: deviceplugin.DevicePlugin.SetLogLevel:output_type -> deviceplugin.Empty
	0,  // 15: deviceplugin.DevicePlugin.Start:output_type -> deviceplugin.Empty
	0,  // 16: deviceplugin.DevicePlugin.Stop:output_type -> deviceplugin.Empty
	0,  // 17: deviceplugin.DevicePlugin.Pause:output_type -> deviceplugin.Empty
	0,  // 18: deviceplugin.DevicePlugin.HotReload:output_type -> deviceplugin.Empty
	0,  // 19: deviceplugin.DevicePlugin.LoadRuntimeState:output_type -> deviceplugin.Empty
	6,  // 20: deviceplugin.DevicePlugin.SaveRuntimeState:output_type -> deviceplugin.RuntimeState
	7,  // 21: deviceplugin.DevicePlugin.CollectMetrics:output_type -> deviceplugin.MetricsSnapshot
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_examples_device_gateway_deviceplugin_device_plugin_proto_init() }
func file_examples_device_gateway_deviceplugin_device_plugin_proto_init() {
	if File_examples_device_gateway_deviceplugin_device_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDesc), len(file_examples_device_gateway_deviceplugin_device_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_device_gateway_deviceplugin_device_plugin_proto_goTypes,
		DependencyIndexes: file_examples_device_gateway_deviceplugin_device_plugin_proto_depIdxs,
		MessageInfos:      file_examples_device_gateway_deviceplugin_device_plugin_proto_msgTypes,
	}.Build()
	File_examples_device_gateway_deviceplugin_device_plugin_proto = out.File
	file_examples_device_gateway_deviceplugin_device_plugin_proto_goTypes = nil
	file_examples_device_gateway_deviceplugin_device_plugin_proto_depIdxs = nil
}
