// Command echoroundtrip-host spawns the echo plugin and calls its Say RPC,
// verifying that code generated by protoc-gen-go-styx can execute real
// calls end-to-end: from NewEchoClient through the handshake to the spawned
// plugin process and back. The test builds this binary fresh against a
// freshly generated echopb package to prove the generated code actually works,
// not just that its source text looks correct.
//
// Usage: echoroundtrip-host <path-to-echoroundtrip-plugin-binary>
//
// On success, prints the plugin's response message and exits 0.
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/arloliu/styx"
	"github.com/arloliu/styx/cmd/protoc-gen-go-styx/testdata/echoroundtrip/echopb"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: echoroundtrip-host <plugin-path>")
		os.Exit(2)
	}

	h := styx.NewHost(styx.HostConfig{
		Plugins: []styx.PluginSpec{{Name: "echo", Path: os.Args[1]}},
	})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := h.Start(ctx); err != nil {
		fmt.Fprintln(os.Stderr, "start:", err)
		os.Exit(1)
	}
	defer func() { _ = h.Stop(ctx) }()

	client := echopb.NewEchoClient(h.Plugin("echo"))

	resp, err := client.Say(ctx, &echopb.SayRequest{Message: "hi"})
	if err != nil {
		fmt.Fprintln(os.Stderr, "say:", err)
		os.Exit(1)
	}

	fmt.Println(resp.GetMessage())
}
