// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: internal/control/control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint64                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControlMessage_Hello
	//	*ControlMessage_HelloAck
	//	*ControlMessage_AttachRegion
	//	*ControlMessage_AttachRegionAck
	//	*ControlMessage_Heartbeat
	//	*ControlMessage_HeartbeatAck
	//	*ControlMessage_Drain
	//	*ControlMessage_DrainAck
	//	*ControlMessage_Resume
	//	*ControlMessage_ResumeAck
	//	*ControlMessage_SaveState
	//	*ControlMessage_SaveStateAck
	//	*ControlMessage_Shutdown
	//	*ControlMessage_ShutdownAck
	//	*ControlMessage_Poisoned
	//	*ControlMessage_Restore
	//	*ControlMessage_RestoreAck
	Body          isControlMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_internal_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetCorrelationId() uint64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *ControlMessage) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ControlMessage) GetBody() isControlMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControlMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ControlMessage) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ControlMessage) GetAttachRegion() *AttachRegion {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_AttachRegion); ok {
			return x.AttachRegion
		}
	}
	return nil
}

func (x *ControlMessage) GetAttachRegionAck() *AttachRegionAck {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_AttachRegionAck); ok {
			return x.AttachRegionAck
		}
	}
	return nil
}

func (x *ControlMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ControlMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ControlMessage) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *ControlMessage) GetDrainAck() *DrainAck {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_DrainAck); ok {
			return x.DrainAck
		}
	}
	return nil
}

func (x *ControlMessage) GetResume() *Resume {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *ControlMessage) GetResumeAck() *ResumeAck {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_ResumeAck); ok {
			return x.ResumeAck
		}
	}
	return nil
}

func (x *ControlMessage) GetSaveState() *SaveState {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_SaveState); ok {
			return x.SaveState
		}
	}
	return nil
}

func (x *ControlMessage) GetSaveStateAck() *SaveStateAck {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_SaveStateAck); ok {
			return x.SaveStateAck
		}
	}
	return nil
}

func (x *ControlMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ControlMessage) GetShutdownAck() *ShutdownAck {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_ShutdownAck); ok {
			return x.ShutdownAck
		}
	}
	return nil
}

func (x *ControlMessage) GetPoisoned() *Poisoned {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Poisoned); ok {
			return x.Poisoned
		}
	}
	return nil
}

func (x *ControlMessage) GetRestore() *Restore {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

func (x *ControlMessage) GetRestoreAck() *RestoreAck {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_RestoreAck); ok {
			return x.RestoreAck
		}
	}
	return nil
}

type isControlMessage_Body interface {
	isControlMessage_Body()
}

type ControlMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,3,opt,name=hello,proto3,oneof"`
}

type ControlMessage_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,4,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ControlMessage_AttachRegion struct {
	AttachRegion *AttachRegion `protobuf:"bytes,5,opt,name=attach_region,json=attachRegion,proto3,oneof"`
}

type ControlMessage_AttachRegionAck struct {
	AttachRegionAck *AttachRegionAck `protobuf:"bytes,6,opt,name=attach_region_ack,json=attachRegionAck,proto3,oneof"`
}

type ControlMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,7,opt,name=heartbeat,proto3,oneof"`
}

type ControlMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,8,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ControlMessage_Drain struct {
	Drain *Drain `protobuf:"bytes,9,opt,name=drain,proto3,oneof"`
}

type ControlMessage_DrainAck struct {
	DrainAck *DrainAck `protobuf:"bytes,10,opt,name=drain_ack,json=drainAck,proto3,oneof"`
}

type ControlMessage_Resume struct {
	Resume *Resume `protobuf:"bytes,11,opt,name=resume,proto3,oneof"`
}

type ControlMessage_ResumeAck struct {
	ResumeAck *ResumeAck `protobuf:"bytes,12,opt,name=resume_ack,json=resumeAck,proto3,oneof"`
}

type ControlMessage_SaveState struct {
	SaveState *SaveState `protobuf:"bytes,13,opt,name=save_state,json=saveState,proto3,oneof"`
}

type ControlMessage_SaveStateAck struct {
	SaveStateAck *SaveStateAck `protobuf:"bytes,14,opt,name=save_state_ack,json=saveStateAck,proto3,oneof"`
}

type ControlMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,15,opt,name=shutdown,proto3,oneof"`
}

type ControlMessage_ShutdownAck struct {
	ShutdownAck *ShutdownAck `protobuf:"bytes,16,opt,name=shutdown_ack,json=shutdownAck,proto3,oneof"`
}

type ControlMessage_Poisoned struct {
	Poisoned *Poisoned `protobuf:"bytes,17,opt,name=poisoned,proto3,oneof"`
}

type ControlMessage_Restore struct {
	Restore *Restore `protobuf:"bytes,18,opt,name=restore,proto3,oneof"`
}

type ControlMessage_RestoreAck struct {
	RestoreAck *RestoreAck `protobuf:"bytes,19,opt,name=restore_ack,json=restoreAck,proto3,oneof"`
}

func (*ControlMessage_Hello) isControlMessage_Body() {}

func (*ControlMessage_HelloAck) isControlMessage_Body() {}

func (*ControlMessage_AttachRegion) isControlMessage_Body() {}

func (*ControlMessage_AttachRegionAck) isControlMessage_Body() {}

func (*ControlMessage_Heartbeat) isControlMessage_Body() {}

func (*ControlMessage_HeartbeatAck) isControlMessage_Body() {}

func (*ControlMessage_Drain) isControlMessage_Body() {}

func (*ControlMessage_DrainAck) isControlMessage_Body() {}

func (*ControlMessage_Resume) isControlMessage_Body() {}

func (*ControlMessage_ResumeAck) isControlMessage_Body() {}

func (*ControlMessage_SaveState) isControlMessage_Body() {}

func (*ControlMessage_SaveStateAck) isControlMessage_Body() {}

func (*ControlMessage_Shutdown) isControlMessage_Body() {}

func (*ControlMessage_ShutdownAck) isControlMessage_Body() {}

func (*ControlMessage_Poisoned) isControlMessage_Body() {}

func (*ControlMessage_Restore) isControlMessage_Body() {}

func (*ControlMessage_RestoreAck) isControlMessage_Body() {}

type FeatureFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Supported     bool                   `protobuf:"varint,3,opt,name=supported,proto3" json:"supported,omitempty"` // set by the receiver when echoing in HelloAck
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureFlag) Reset() {
	*x = FeatureFlag{}
	mi := &file_internal_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureFlag) ProtoMessage() {}

func (x *FeatureFlag) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureFlag.ProtoReflect.Descriptor instead.
func (*FeatureFlag) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureFlag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeatureFlag) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FeatureFlag) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

type ServiceRequirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	MinVersion    uint32                 `protobuf:"varint,2,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MaxVersion    uint32                 `protobuf:"varint,3,opt,name=max_version,json=maxVersion,proto3" json:"max_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRequirement) Reset() {
	*x = ServiceRequirement{}
	mi := &file_internal_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequirement) ProtoMessage() {}

func (x *ServiceRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequirement.ProtoReflect.Descriptor instead.
func (*ServiceRequirement) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceRequirement) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceRequirement) GetMinVersion() uint32 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

func (x *ServiceRequirement) GetMaxVersion() uint32 {
	if x != nil {
		return x.MaxVersion
	}
	return 0
}

type ServiceVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceVersion) Reset() {
	*x = ServiceVersion{}
	mi := &file_internal_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceVersion) ProtoMessage() {}

func (x *ServiceVersion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceVersion.ProtoReflect.Descriptor instead.
func (*ServiceVersion) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceVersion) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceVersion) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMin   uint32                 `protobuf:"varint,1,opt,name=protocol_min,json=protocolMin,proto3" json:"protocol_min,omitempty"`
	ProtocolMax   uint32                 `protobuf:"varint,2,opt,name=protocol_max,json=protocolMax,proto3" json:"protocol_max,omitempty"`
	Features      []*FeatureFlag         `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	Transports    []string               `protobuf:"bytes,4,rep,name=transports,proto3" json:"transports,omitempty"`
	Codecs        []string               `protobuf:"bytes,5,rep,name=codecs,proto3" json:"codecs,omitempty"`
	Nonce         uint64                 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Services      []*ServiceRequirement  `protobuf:"bytes,7,rep,name=services,proto3" json:"services,omitempty"` // host->plugin only; empty from plugin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetProtocolMin() uint32 {
	if x != nil {
		return x.ProtocolMin
	}
	return 0
}

func (x *Hello) GetProtocolMax() uint32 {
	if x != nil {
		return x.ProtocolMax
	}
	return 0
}

func (x *Hello) GetFeatures() []*FeatureFlag {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Hello) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *Hello) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

func (x *Hello) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Hello) GetServices() []*ServiceRequirement {
	if x != nil {
		return x.Services
	}
	return nil
}

type HelloAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Transport       string                 `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	LayoutVersion   uint32                 `protobuf:"varint,3,opt,name=layout_version,json=layoutVersion,proto3" json:"layout_version,omitempty"` // 0 unless transport == "shm"
	Features        []*FeatureFlag         `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty"`
	Codec           string                 `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	Nonce           uint64                 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"` // echoed from Hello
	PluginName      string                 `protobuf:"bytes,7,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	PluginSemver    string                 `protobuf:"bytes,8,opt,name=plugin_semver,json=pluginSemver,proto3" json:"plugin_semver,omitempty"`
	BinarySha256    string                 `protobuf:"bytes,9,opt,name=binary_sha256,json=binarySha256,proto3" json:"binary_sha256,omitempty"`
	Services        []*ServiceVersion      `protobuf:"bytes,10,rep,name=services,proto3" json:"services,omitempty"`
	// incompatible_reason, when non-empty, marks this HelloAck as a
	// negotiation-rejection reply rather than a success ack: a plugin that
	// cannot satisfy the host's per-service requirements fails handshake
	// with the offending service named in the error. The plugin still
	// replies (echoing nonce) instead of silently closing, so the host
	// can reconstruct a typed IncompatibleError instead of observing an
	// undifferentiated connection loss. Every other field is unset on a
	// rejection reply.
	IncompatibleReason string `protobuf:"bytes,11,opt,name=incompatible_reason,json=incompatibleReason,proto3" json:"incompatible_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_internal_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{5}
}

func (x *HelloAck) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloAck) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *HelloAck) GetLayoutVersion() uint32 {
	if x != nil {
		return x.LayoutVersion
	}
	return 0
}

func (x *HelloAck) GetFeatures() []*FeatureFlag {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *HelloAck) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *HelloAck) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *HelloAck) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *HelloAck) GetPluginSemver() string {
	if x != nil {
		return x.PluginSemver
	}
	return ""
}

func (x *HelloAck) GetBinarySha256() string {
	if x != nil {
		return x.BinarySha256
	}
	return ""
}

func (x *HelloAck) GetServices() []*ServiceVersion {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *HelloAck) GetIncompatibleReason() string {
	if x != nil {
		return x.IncompatibleReason
	}
	return ""
}

type AttachRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	LayoutSize    uint64                 `protobuf:"varint,2,opt,name=layout_size,json=layoutSize,proto3" json:"layout_size,omitempty"`
	LayoutVersion uint32                 `protobuf:"varint,3,opt,name=layout_version,json=layoutVersion,proto3" json:"layout_version,omitempty"`
	FdCount       uint32                 `protobuf:"varint,4,opt,name=fd_count,json=fdCount,proto3" json:"fd_count,omitempty"` // declared fd count carried via SCM_RIGHTS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRegion) Reset() {
	*x = AttachRegion{}
	mi := &file_internal_control_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRegion) ProtoMessage() {}

func (x *AttachRegion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRegion.ProtoReflect.Descriptor instead.
func (*AttachRegion) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{6}
}

func (x *AttachRegion) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *AttachRegion) GetLayoutSize() uint64 {
	if x != nil {
		return x.LayoutSize
	}
	return 0
}

func (x *AttachRegion) GetLayoutVersion() uint32 {
	if x != nil {
		return x.LayoutVersion
	}
	return 0
}

func (x *AttachRegion) GetFdCount() uint32 {
	if x != nil {
		return x.FdCount
	}
	return 0
}

type AttachRegionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRegionAck) Reset() {
	*x = AttachRegionAck{}
	mi := &file_internal_control_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRegionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRegionAck) ProtoMessage() {}

func (x *AttachRegionAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRegionAck.ProtoReflect.Descriptor instead.
func (*AttachRegionAck) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{7}
}

type ActiveHandlerLease struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CallId               uint64                 `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	StartUnixNano        int64                  `protobuf:"varint,2,opt,name=start_unix_nano,json=startUnixNano,proto3" json:"start_unix_nano,omitempty"`
	LeaseRenewedUnixNano int64                  `protobuf:"varint,3,opt,name=lease_renewed_unix_nano,json=leaseRenewedUnixNano,proto3" json:"lease_renewed_unix_nano,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ActiveHandlerLease) Reset() {
	*x = ActiveHandlerLease{}
	mi := &file_internal_control_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveHandlerLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveHandlerLease) ProtoMessage() {}

func (x *ActiveHandlerLease) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveHandlerLease.ProtoReflect.Descriptor instead.
func (*ActiveHandlerLease) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{8}
}

func (x *ActiveHandlerLease) GetCallId() uint64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *ActiveHandlerLease) GetStartUnixNano() int64 {
	if x != nil {
		return x.StartUnixNano
	}
	return 0
}

func (x *ActiveHandlerLease) GetLeaseRenewedUnixNano() int64 {
	if x != nil {
		return x.LeaseRenewedUnixNano
	}
	return 0
}

type Heartbeat struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Sequence               uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	DescriptorsConsumedH2P uint64                 `protobuf:"varint,2,opt,name=descriptors_consumed_h2p,json=descriptorsConsumedH2p,proto3" json:"descriptors_consumed_h2p,omitempty"`
	DescriptorsProducedP2H uint64                 `protobuf:"varint,3,opt,name=descriptors_produced_p2h,json=descriptorsProducedP2h,proto3" json:"descriptors_produced_p2h,omitempty"`
	InflightCount          uint64                 `protobuf:"varint,4,opt,name=inflight_count,json=inflightCount,proto3" json:"inflight_count,omitempty"`
	ArenaOccupancyBytes    uint64                 `protobuf:"varint,5,opt,name=arena_occupancy_bytes,json=arenaOccupancyBytes,proto3" json:"arena_occupancy_bytes,omitempty"`
	Leases                 []*ActiveHandlerLease  `protobuf:"bytes,6,rep,name=leases,proto3" json:"leases,omitempty"`
	// inbound_readable is the plugin's own report, taken in the same snapshot as
	// descriptors_consumed_h2p, of whether inbound data-plane work is still readable
	// (unconsumed) on its transport. It lets the host judge a stalled ring consumer
	// on one clock — the plugin's — instead of pairing a host send-count with a
	// plugin consume-count across two clocks. A plugin that never sets it (an older
	// build, or a transport that cannot probe its inbound queue) reports false and is
	// never transport-wedged.
	InboundReadable bool `protobuf:"varint,7,opt,name=inbound_readable,json=inboundReadable,proto3" json:"inbound_readable,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_control_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{9}
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Heartbeat) GetDescriptorsConsumedH2P() uint64 {
	if x != nil {
		return x.DescriptorsConsumedH2P
	}
	return 0
}

func (x *Heartbeat) GetDescriptorsProducedP2H() uint64 {
	if x != nil {
		return x.DescriptorsProducedP2H
	}
	return 0
}

func (x *Heartbeat) GetInflightCount() uint64 {
	if x != nil {
		return x.InflightCount
	}
	return 0
}

func (x *Heartbeat) GetArenaOccupancyBytes() uint64 {
	if x != nil {
		return x.ArenaOccupancyBytes
	}
	return 0
}

func (x *Heartbeat) GetLeases() []*ActiveHandlerLease {
	if x != nil {
		return x.Leases
	}
	return nil
}

func (x *Heartbeat) GetInboundReadable() bool {
	if x != nil {
		return x.InboundReadable
	}
	return false
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_internal_control_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatAck) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type Drain struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeadlineUnixNano int64                  `protobuf:"varint,1,opt,name=deadline_unix_nano,json=deadlineUnixNano,proto3" json:"deadline_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_internal_control_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{11}
}

func (x *Drain) GetDeadlineUnixNano() int64 {
	if x != nil {
		return x.DeadlineUnixNano
	}
	return 0
}

type DrainAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainAck) Reset() {
	*x = DrainAck{}
	mi := &file_internal_control_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainAck) ProtoMessage() {}

func (x *DrainAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainAck.ProtoReflect.Descriptor instead.
func (*DrainAck) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{12}
}

type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_internal_control_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{13}
}

type ResumeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeAck) Reset() {
	*x = ResumeAck{}
	mi := &file_internal_control_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAck) ProtoMessage() {}

func (x *ResumeAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAck.ProtoReflect.Descriptor instead.
func (*ResumeAck) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{14}
}

type SaveState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotFdCount uint32                 `protobuf:"varint,1,opt,name=snapshot_fd_count,json=snapshotFdCount,proto3" json:"snapshot_fd_count,omitempty"` // always 1: the sealed snapshot memfd
	DeclaredLength  uint64                 `protobuf:"varint,2,opt,name=declared_length,json=declaredLength,proto3" json:"declared_length,omitempty"`
	FormatVersion   uint32                 `protobuf:"varint,3,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveState) Reset() {
	*x = SaveState{}
	mi := &file_internal_control_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveState) ProtoMessage() {}

func (x *SaveState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveState.ProtoReflect.Descriptor instead.
func (*SaveState) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{15}
}

func (x *SaveState) GetSnapshotFdCount() uint32 {
	if x != nil {
		return x.SnapshotFdCount
	}
	return 0
}

func (x *SaveState) GetDeclaredLength() uint64 {
	if x != nil {
		return x.DeclaredLength
	}
	return 0
}

func (x *SaveState) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

type SaveStateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      []byte                 `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveStateAck) Reset() {
	*x = SaveStateAck{}
	mi := &file_internal_control_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveStateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStateAck) ProtoMessage() {}

func (x *SaveStateAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStateAck.ProtoReflect.Descriptor instead.
func (*SaveStateAck) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{16}
}

func (x *SaveStateAck) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

type Shutdown struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeadlineUnixNano int64                  `protobuf:"varint,1,opt,name=deadline_unix_nano,json=deadlineUnixNano,proto3" json:"deadline_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_internal_control_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{17}
}

func (x *Shutdown) GetDeadlineUnixNano() int64 {
	if x != nil {
		return x.DeadlineUnixNano
	}
	return 0
}

type ShutdownAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownAck) Reset() {
	*x = ShutdownAck{}
	mi := &file_internal_control_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownAck) ProtoMessage() {}

func (x *ShutdownAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownAck.ProtoReflect.Descriptor instead.
func (*ShutdownAck) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{18}
}

type Poisoned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poisoned) Reset() {
	*x = Poisoned{}
	mi := &file_internal_control_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poisoned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poisoned) ProtoMessage() {}

func (x *Poisoned) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poisoned.ProtoReflect.Descriptor instead.
func (*Poisoned) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{19}
}

func (x *Poisoned) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Restore carries a snapshot the host has already verified (full seal set,
// declared length, checksum) to a freshly spawned instance, with the sealed
// memfd attached via SCM_RIGHTS. Host->plugin only.
type Restore struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotFdCount uint32                 `protobuf:"varint,1,opt,name=snapshot_fd_count,json=snapshotFdCount,proto3" json:"snapshot_fd_count,omitempty"` // always 1: the sealed snapshot memfd
	DeclaredLength  uint64                 `protobuf:"varint,2,opt,name=declared_length,json=declaredLength,proto3" json:"declared_length,omitempty"`
	FormatVersion   uint32                 `protobuf:"varint,3,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Restore) Reset() {
	*x = Restore{}
	mi := &file_internal_control_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restore) ProtoMessage() {}

func (x *Restore) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restore.ProtoReflect.Descriptor instead.
func (*Restore) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{20}
}

func (x *Restore) GetSnapshotFdCount() uint32 {
	if x != nil {
		return x.SnapshotFdCount
	}
	return 0
}

func (x *Restore) GetDeclaredLength() uint64 {
	if x != nil {
		return x.DeclaredLength
	}
	return 0
}

func (x *Restore) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

// RestoreAck is the new instance's readiness reply. ready == false aborts
// the reload, and reason says why.
type RestoreAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // populated iff ready == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreAck) Reset() {
	*x = RestoreAck{}
	mi := &file_internal_control_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreAck) ProtoMessage() {}

func (x *RestoreAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreAck.ProtoReflect.Descriptor instead.
func (*RestoreAck) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{21}
}

func (x *RestoreAck) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *RestoreAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_internal_control_control_proto protoreflect.FileDescriptor

const file_internal_control_control_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/control/control.proto\x12\fstyx.control\"\xb7\b\n" +
	"\x0eControlMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\x04R\rcorrelationId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12+\n" +
	"\x05hello\x18\x03 \x01(\v2\x13.styx.control.HelloH\x00R\x05hello\x125\n" +
	"\thello_ack\x18\x04 \x01(\v2\x16.styx.control.HelloAckH\x00R\bhelloAck\x12A\n" +
	"\rattach_region\x18\x05 \x01(\v2\x1a.styx.control.AttachRegionH\x00R\fattachRegion\x12K\n" +
	"\x11attach_region_ack\x18\x06 \x01(\v2\x1d.styx.control.AttachRegionAckH\x00R\x0fattachRegionAck\x127\n" +
	"\theartbeat\x18\a \x01(\v2\x17.styx.control.HeartbeatH\x00R\theartbeat\x12A\n" +
	"\rheartbeat_ack\x18\b \x01(\v2\x1a.styx.control.HeartbeatAckH\x00R\fheartbeatAck\x12+\n" +
	"\x05drain\x18\t \x01(\v2\x13.styx.control.DrainH\x00R\x05drain\x125\n" +
	"\tdrain_ack\x18\n" +
	" \x01(\v2\x16.styx.control.DrainAckH\x00R\bdrainAck\x12.\n" +
	"\x06resume\x18\v \x01(\v2\x14.styx.control.ResumeH\x00R\x06resume\x128\n" +
	"\n" +
	"resume_ack\x18\f \x01(\v2\x17.styx.control.ResumeAckH\x00R\tresumeAck\x128\n" +
	"\n" +
	"save_state\x18\r \x01(\v2\x17.styx.control.SaveStateH\x00R\tsaveState\x12B\n" +
	"\x0esave_state_ack\x18\x0e \x01(\v2\x1a.styx.control.SaveStateAckH\x00R\fsaveStateAck\x124\n" +
	"\bshutdown\x18\x0f \x01(\v2\x16.styx.control.ShutdownH\x00R\bshutdown\x12>\n" +
	"\fshutdown_ack\x18\x10 \x01(\v2\x19.styx.control.ShutdownAckH\x00R\vshutdownAck\x124\n" +
	"\bpoisoned\x18\x11 \x01(\v2\x16.styx.control.PoisonedH\x00R\bpoisoned\x121\n" +
	"\arestore\x18\x12 \x01(\v2\x15.styx.control.RestoreH\x00R\arestore\x12;\n" +
	"\vrestore_ack\x18\x13 \x01(\v2\x18.styx.control.RestoreAckH\x00R\n" +
	"restoreAckB\x06\n" +
	"\x04body\"[\n" +
	"\vFeatureFlag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12\x1c\n" +
	"\tsupported\x18\x03 \x01(\bR\tsupported\"p\n" +
	"\x12ServiceRequirement\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1f\n" +
	"\vmin_version\x18\x02 \x01(\rR\n" +
	"minVersion\x12\x1f\n" +
	"\vmax_version\x18\x03 \x01(\rR\n" +
	"maxVersion\"D\n" +
	"\x0eServiceVersion\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\"\x90\x02\n" +
	"\x05Hello\x12!\n" +
	"\fprotocol_min\x18\x01 \x01(\rR\vprotocolMin\x12!\n" +
	"\fprotocol_max\x18\x02 \x01(\rR\vprotocolMax\x125\n" +
	"\bfeatures\x18\x03 \x03(\v2\x19.styx.control.FeatureFlagR\bfeatures\x12\x1e\n" +
	"\n" +
	"transports\x18\x04 \x03(\tR\n" +
	"transports\x12\x16\n" +
	"\x06codecs\x18\x05 \x03(\tR\x06codecs\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x12<\n" +
	"\bservices\x18\a \x03(\v2 .styx.control.ServiceRequirementR\bservices\"\xb3\x03\n" +
	"\bHelloAck\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12%\n" +
	"\x0elayout_version\x18\x03 \x01(\rR\rlayoutVersion\x125\n" +
	"\bfeatures\x18\x04 \x03(\v2\x19.styx.control.FeatureFlagR\bfeatures\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x12\x1f\n" +
	"\vplugin_name\x18\a \x01(\tR\n" +
	"pluginName\x12#\n" +
	"\rplugin_semver\x18\b \x01(\tR\fpluginSemver\x12#\n" +
	"\rbinary_sha256\x18\t \x01(\tR\fbinarySha256\x128\n" +
	"\bservices\x18\n" +
	" \x03(\v2\x1c.styx.control.ServiceVersionR\bservices\x12/\n" +
	"\x13incompatible_reason\x18\v \x01(\tR\x12incompatibleReason\"\x91\x01\n" +
	"\fAttachRegion\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x1f\n" +
	"\vlayout_size\x18\x02 \x01(\x04R\n" +
	"layoutSize\x12%\n" +
	"\x0elayout_version\x18\x03 \x01(\rR\rlayoutVersion\x12\x19\n" +
	"\bfd_count\x18\x04 \x01(\rR\afdCount\"\x11\n" +
	"\x0fAttachRegionAck\"\x8c\x01\n" +
	"\x12ActiveHandlerLease\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\x04R\x06callId\x12&\n" +
	"\x0fstart_unix_nano\x18\x02 \x01(\x03R\rstartUnixNano\x125\n" +
	"\x17lease_renewed_unix_nano\x18\x03 \x01(\x03R\x14leaseRenewedUnixNano\"\xdb\x02\n" +
	"\tHeartbeat\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x128\n" +
	"\x18descriptors_consumed_h2p\x18\x02 \x01(\x04R\x16descriptorsConsumedH2p\x128\n" +
	"\x18descriptors_produced_p2h\x18\x03 \x01(\x04R\x16descriptorsProducedP2h\x12%\n" +
	"\x0einflight_count\x18\x04 \x01(\x04R\rinflightCount\x122\n" +
	"\x15arena_occupancy_bytes\x18\x05 \x01(\x04R\x13arenaOccupancyBytes\x128\n" +
	"\x06leases\x18\x06 \x03(\v2 .styx.control.ActiveHandlerLeaseR\x06leases\x12)\n" +
	"\x10inbound_readable\x18\a \x01(\bR\x0finboundReadable\"*\n" +
	"\fHeartbeatAck\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"5\n" +
	"\x05Drain\x12,\n" +
	"\x12deadline_unix_nano\x18\x01 \x01(\x03R\x10deadlineUnixNano\"\n" +
	"\n" +
	"\bDrainAck\"\b\n" +
	"\x06Resume\"\v\n" +
	"\tResumeAck\"\x87\x01\n" +
	"\tSaveState\x12*\n" +
	"\x11snapshot_fd_count\x18\x01 \x01(\rR\x0fsnapshotFdCount\x12'\n" +
	"\x0fdeclared_length\x18\x02 \x01(\x04R\x0edeclaredLength\x12%\n" +
	"\x0eformat_version\x18\x03 \x01(\rR\rformatVersion\"*\n" +
	"\fSaveStateAck\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\fR\bchecksum\"8\n" +
	"\bShutdown\x12,\n" +
	"\x12deadline_unix_nano\x18\x01 \x01(\x03R\x10deadlineUnixNano\"\r\n" +
	"\vShutdownAck\"\"\n" +
	"\bPoisoned\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x85\x01\n" +
	"\aRestore\x12*\n" +
	"\x11snapshot_fd_count\x18\x01 \x01(\rR\x0fsnapshotFdCount\x12'\n" +
	"\x0fdeclared_length\x18\x02 \x01(\x04R\x0edeclaredLength\x12%\n" +
	"\x0eformat_version\x18\x03 \x01(\rR\rformatVersion\":\n" +
	"\n" +
	"RestoreAck\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB4Z2github.com/arloliu/styx/internal/control/controlpbb\x06proto3"

var (
	file_internal_control_control_proto_rawDescOnce sync.Once
	file_internal_control_control_proto_rawDescData []byte
)

func file_internal_control_control_proto_rawDescGZIP() []byte {
	file_internal_control_control_proto_rawDescOnce.Do(func() {
		file_internal_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_control_control_proto_rawDesc), len(file_internal_control_control_proto_rawDesc)))
	})
	return file_internal_control_control_proto_rawDescData
}

var file_internal_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_control_control_proto_goTypes = []any{
	(*ControlMessage)(nil),     // 0: styx.control.ControlMessage
	(*FeatureFlag)(nil),        // 1: styx.control.FeatureFlag
	(*ServiceRequirement)(nil), // 2: styx.control.ServiceRequirement
	(*ServiceVersion)(nil),     // 3: styx.control.ServiceVersion
	(*Hello)(nil),              // 4: styx.control.Hello
	(*HelloAck)(nil),           // 5: styx.control.HelloAck
	(*AttachRegion)(nil),       // 6: styx.control.AttachRegion
	(*AttachRegionAck)(nil),    // 7: styx.control.AttachRegionAck
	(*ActiveHandlerLease)(nil), // 8: styx.control.ActiveHandlerLease
	(*Heartbeat)(nil),          // 9: styx.control.Heartbeat
	(*HeartbeatAck)(nil),       // 10: styx.control.HeartbeatAck
	(*Drain)(nil),              // 11: styx.control.Drain
	(*DrainAck)(nil),           // 12: styx.control.DrainAck
	(*Resume)(nil),             // 13: styx.control.Resume
	(*ResumeAck)(nil),          // 14: styx.control.ResumeAck
	(*SaveState)(nil),          // 15: styx.control.SaveState
	(*SaveStateAck)(nil),       // 16: styx.control.SaveStateAck
	(*Shutdown)(nil),           // 17: styx.control.Shutdown
	(*ShutdownAck)(nil),        // 18: styx.control.ShutdownAck
	(*Poisoned)(nil),           // 19: styx.control.Poisoned
	(*Restore)(nil),            // 20: styx.control.Restore
	(*RestoreAck)(nil),         // 21: styx.control.RestoreAck
}
var file_internal_control_control_proto_depIdxs = []int32{
	4,  // 0: styx.control.ControlMessage.hello:type_name -> styx.control.Hello
	5,  // 1: styx.control.ControlMessage.hello_ack:type_name -> styx.control.HelloAck
	6,  // 2: styx.control.ControlMessage.attach_region:type_name -> styx.control.AttachRegion
	7,  // 3: styx.control.ControlMessage.attach_region_ack:type_name -> styx.control.AttachRegionAck
	9,  // 4: styx.control.ControlMessage.heartbeat:type_name -> styx.control.Heartbeat
	10, // 5: styx.control.ControlMessage.heartbeat_ack:type_name -> styx.control.HeartbeatAck
	11, // 6: styx.control.ControlMessage.drain:type_name -> styx.control.Drain
	12, // 7: styx.control.ControlMessage.drain_ack:type_name -> styx.control.DrainAck
	13, // 8: styx.control.ControlMessage.resume:type_name -> styx.control.Resume
	14, // 9: styx.control.ControlMessage.resume_ack:type_name -> styx.control.ResumeAck
	15, // 10: styx.control.ControlMessage.save_state:type_name -> styx.control.SaveState
	16, // 11: styx.control.ControlMessage.save_state_ack:type_name -> styx.control.SaveStateAck
	17, // 12: styx.control.ControlMessage.shutdown:type_name -> styx.control.Shutdown
	18, // 13: styx.control.ControlMessage.shutdown_ack:type_name -> styx.control.ShutdownAck
	19, // 14: styx.control.ControlMessage.poisoned:type_name -> styx.control.Poisoned
	20, // 15: styx.control.ControlMessage.restore:type_name -> styx.control.Restore
	21, // 16: styx.control.ControlMessage.restore_ack:type_name -> styx.control.RestoreAck
	1,  // 17: styx.control.Hello.features:type_name -> styx.control.FeatureFlag
	2,  // 18: styx.control.Hello.services:type_name -> styx.control.ServiceRequirement
	1,  // 19: styx.control.HelloAck.features:type_name -> styx.control.FeatureFlag
	3,  // 20: styx.control.HelloAck.services:type_name -> styx.control.ServiceVersion
	8,  // 21: styx.control.Heartbeat.leases:type_name -> styx.control.ActiveHandlerLease
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_internal_control_control_proto_init() }
func file_internal_control_control_proto_init() {
	if File_internal_control_control_proto != nil {
		return
	}
	file_internal_control_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_Hello)(nil),
		(*ControlMessage_HelloAck)(nil),
		(*ControlMessage_AttachRegion)(nil),
		(*ControlMessage_AttachRegionAck)(nil),
		(*ControlMessage_Heartbeat)(nil),
		(*ControlMessage_HeartbeatAck)(nil),
		(*ControlMessage_Drain)(nil),
		(*ControlMessage_DrainAck)(nil),
		(*ControlMessage_Resume)(nil),
		(*ControlMessage_ResumeAck)(nil),
		(*ControlMessage_SaveState)(nil),
		(*ControlMessage_SaveStateAck)(nil),
		(*ControlMessage_Shutdown)(nil),
		(*ControlMessage_ShutdownAck)(nil),
		(*ControlMessage_Poisoned)(nil),
		(*ControlMessage_Restore)(nil),
		(*ControlMessage_RestoreAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_control_control_proto_rawDesc), len(file_internal_control_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_control_control_proto_goTypes,
		DependencyIndexes: file_internal_control_control_proto_depIdxs,
		MessageInfos:      file_internal_control_control_proto_msgTypes,
	}.Build()
	File_internal_control_control_proto = out.File
	file_internal_control_control_proto_goTypes = nil
	file_internal_control_control_proto_depIdxs = nil
}
