// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: codec/internal/testpb/everything.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Everything is a test-only message exercising every field kind the codec's
// vtprotobuf fast path must round-trip: scalars, bytes, repeated, map, oneof,
// and a nested message. It is generated by the same buf run as the repo's real
// messages, so it gains MarshalVT/UnmarshalVT and drives the cross-decode
// matrix and the codec dispatch benchmarks.
type Everything struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	I32         int32                  `protobuf:"varint,1,opt,name=i32,proto3" json:"i32,omitempty"`
	I64         int64                  `protobuf:"varint,2,opt,name=i64,proto3" json:"i64,omitempty"`
	U32         uint32                 `protobuf:"varint,3,opt,name=u32,proto3" json:"u32,omitempty"`
	U64         uint64                 `protobuf:"varint,4,opt,name=u64,proto3" json:"u64,omitempty"`
	Flag        bool                   `protobuf:"varint,5,opt,name=flag,proto3" json:"flag,omitempty"`
	Text        string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Payload     []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	Real        float64                `protobuf:"fixed64,8,opt,name=real,proto3" json:"real,omitempty"`
	Numbers     []int32                `protobuf:"varint,9,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Tags        []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Counts      map[string]int32       `protobuf:"bytes,11,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	NestedByKey map[string]*Nested     `protobuf:"bytes,12,rep,name=nested_by_key,json=nestedByKey,proto3" json:"nested_by_key,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Nested      *Nested                `protobuf:"bytes,13,opt,name=nested,proto3" json:"nested,omitempty"`
	// Types that are valid to be assigned to Choice:
	//
	//	*Everything_ChoiceInt
	//	*Everything_ChoiceText
	//	*Everything_ChoiceNested
	Choice        isEverything_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Everything) Reset() {
	*x = Everything{}
	mi := &file_codec_internal_testpb_everything_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Everything) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Everything) ProtoMessage() {}

func (x *Everything) ProtoReflect() protoreflect.Message {
	mi := &file_codec_internal_testpb_everything_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Everything.ProtoReflect.Descriptor instead.
func (*Everything) Descriptor() ([]byte, []int) {
	return file_codec_internal_testpb_everything_proto_rawDescGZIP(), []int{0}
}

func (x *Everything) GetI32() int32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *Everything) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *Everything) GetU32() uint32 {
	if x != nil {
		return x.U32
	}
	return 0
}

func (x *Everything) GetU64() uint64 {
	if x != nil {
		return x.U64
	}
	return 0
}

func (x *Everything) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *Everything) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Everything) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Everything) GetReal() float64 {
	if x != nil {
		return x.Real
	}
	return 0
}

func (x *Everything) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *Everything) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Everything) GetCounts() map[string]int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *Everything) GetNestedByKey() map[string]*Nested {
	if x != nil {
		return x.NestedByKey
	}
	return nil
}

func (x *Everything) GetNested() *Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Everything) GetChoice() isEverything_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *Everything) GetChoiceInt() int32 {
	if x != nil {
		if x, ok := x.Choice.(*Everything_ChoiceInt); ok {
			return x.ChoiceInt
		}
	}
	return 0
}

func (x *Everything) GetChoiceText() string {
	if x != nil {
		if x, ok := x.Choice.(*Everything_ChoiceText); ok {
			return x.ChoiceText
		}
	}
	return ""
}

func (x *Everything) GetChoiceNested() *Nested {
	if x != nil {
		if x, ok := x.Choice.(*Everything_ChoiceNested); ok {
			return x.ChoiceNested
		}
	}
	return nil
}

type isEverything_Choice interface {
	isEverything_Choice()
}

type Everything_ChoiceInt struct {
	ChoiceInt int32 `protobuf:"varint,14,opt,name=choice_int,json=choiceInt,proto3,oneof"`
}

type Everything_ChoiceText struct {
	ChoiceText string `protobuf:"bytes,15,opt,name=choice_text,json=choiceText,proto3,oneof"`
}

type Everything_ChoiceNested struct {
	ChoiceNested *Nested `protobuf:"bytes,16,opt,name=choice_nested,json=choiceNested,proto3,oneof"`
}

func (*Everything_ChoiceInt) isEverything_Choice() {}

func (*Everything_ChoiceText) isEverything_Choice() {}

func (*Everything_ChoiceNested) isEverything_Choice() {}

// Nested is embedded and repeated inside Everything to exercise message-typed
// fields, map values, and oneof arms.
type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_codec_internal_testpb_everything_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_codec_internal_testpb_everything_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_codec_internal_testpb_everything_proto_rawDescGZIP(), []int{1}
}

func (x *Nested) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Nested) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_codec_internal_testpb_everything_proto protoreflect.FileDescriptor

const file_codec_internal_testpb_everything_proto_rawDesc = "" +
	"\n" +
	"&codec/internal/testpb/everything.proto\x12\x11styx.codec.testpb\"\xc8\x05\n" +
	"\n" +
	"Everything\x12\x10\n" +
	"\x03i32\x18\x01 \x01(\x05R\x03i32\x12\x10\n" +
	"\x03i64\x18\x02 \x01(\x03R\x03i64\x12\x10\n" +
	"\x03u32\x18\x03 \x01(\rR\x03u32\x12\x10\n" +
	"\x03u64\x18\x04 \x01(\x04R\x03u64\x12\x12\n" +
	"\x04flag\x18\x05 \x01(\bR\x04flag\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x12\n" +
	"\x04real\x18\b \x01(\x01R\x04real\x12\x18\n" +
	"\anumbers\x18\t \x03(\x05R\anumbers\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12A\n" +
	"\x06counts\x18\v \x03(\v2).styx.codec.testpb.Everything.CountsEntryR\x06counts\x12R\n" +
	"\rnested_by_key\x18\f \x03(\v2..styx.codec.testpb.Everything.NestedByKeyEntryR\vnestedByKey\x121\n" +
	"\x06nested\x18\r \x01(\v2\x19.styx.codec.testpb.NestedR\x06nested\x12\x1f\n" +
	"\n" +
	"choice_int\x18\x0e \x01(\x05H\x00R\tchoiceInt\x12!\n" +
	"\vchoice_text\x18\x0f \x01(\tH\x00R\n" +
	"choiceText\x12@\n" +
	"\rchoice_nested\x18\x10 \x01(\v2\x19.styx.codec.testpb.NestedH\x00R\fchoiceNested\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aY\n" +
	"\x10NestedByKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.styx.codec.testpb.NestedR\x05value:\x028\x01B\b\n" +
	"\x06choice\"2\n" +
	"\x06Nested\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05valueB/Z-github.com/arloliu/styx/codec/internal/testpbb\x06proto3"

var (
	file_codec_internal_testpb_everything_proto_rawDescOnce sync.Once
	file_codec_internal_testpb_everything_proto_rawDescData []byte
)

func file_codec_internal_testpb_everything_proto_rawDescGZIP() []byte {
	file_codec_internal_testpb_everything_proto_rawDescOnce.Do(func() {
		file_codec_internal_testpb_everything_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codec_internal_testpb_everything_proto_rawDesc), len(file_codec_internal_testpb_everything_proto_rawDesc)))
	})
	return file_codec_internal_testpb_everything_proto_rawDescData
}

var file_codec_internal_testpb_everything_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_codec_internal_testpb_everything_proto_goTypes = []any{
	(*Everything)(nil), // 0: styx.codec.testpb.Everything
	(*Nested)(nil),     // 1: styx.codec.testpb.Nested
	nil,                // 2: styx.codec.testpb.Everything.CountsEntry
	nil,                // 3: styx.codec.testpb.Everything.NestedByKeyEntry
}
var file_codec_internal_testpb_everything_proto_depIdxs = []int32{
	2, // 0: styx.codec.testpb.Everything.counts:type_name -> styx.codec.testpb.Everything.CountsEntry
	3, // 1: styx.codec.testpb.Everything.nested_by_key:type_name -> styx.codec.testpb.Everything.NestedByKeyEntry
	1, // 2: styx.codec.testpb.Everything.nested:type_name -> styx.codec.testpb.Nested
	1, // 3: styx.codec.testpb.Everything.choice_nested:type_name -> styx.codec.testpb.Nested
	1, // 4: styx.codec.testpb.Everything.NestedByKeyEntry.value:type_name -> styx.codec.testpb.Nested
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_codec_internal_testpb_everything_proto_init() }
func file_codec_internal_testpb_everything_proto_init() {
	if File_codec_internal_testpb_everything_proto != nil {
		return
	}
	file_codec_internal_testpb_everything_proto_msgTypes[0].OneofWrappers = []any{
		(*Everything_ChoiceInt)(nil),
		(*Everything_ChoiceText)(nil),
		(*Everything_ChoiceNested)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codec_internal_testpb_everything_proto_rawDesc), len(file_codec_internal_testpb_everything_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codec_internal_testpb_everything_proto_goTypes,
		DependencyIndexes: file_codec_internal_testpb_everything_proto_depIdxs,
		MessageInfos:      file_codec_internal_testpb_everything_proto_msgTypes,
	}.Build()
	File_codec_internal_testpb_everything_proto = out.File
	file_codec_internal_testpb_everything_proto_goTypes = nil
	file_codec_internal_testpb_everything_proto_depIdxs = nil
}
